# Generated by Django 2.2.dev20190130093405 on 2019-01-31 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturalkey', '0003_auto_20190131_0258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name')},
        ),
    ]
