# Generated by Django 2.2.dev20190130093405 on 2019-01-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturalkey', '0005_citymodel_countrymodel_statemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrymodel',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='statemodel',
            name='abbreviation',
        ),
    ]
