# Generated by Django 2.2.dev20190130093405 on 2019-01-31 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturalkey', '0006_auto_20190131_0404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityModel',
        ),
    ]
